### ISSUE TITLE
not finding serial COM ports

### ISSUE THREAD

**Issue by truufseir** [Arkans428/SIM7600G-H-Voice-Call-Dialer#4]
PS K:\SIM7600G-H-Serial-Audio\CellDialer\CellDialer> dotnet run
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'COM23'.
File name: 'COM23'
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
   at ModemTool.SerialAudioPhone.StartSmsMonitoring()
   at ModemTool.Program.Main(String[] args)

**Comment by truufseir** [comment]
this is on a windows build for windows 11

**Comment by Arkans428** [comment]
Could you post a screenshot of your device manager showing all your serial ports?

**Comment by truufseir** [comment]
ok i had to reinstall the driver for it to work so i don't have the screenshot but i got it working ... can't send audio however but can do dtmf tones is this the functionality so far

**Comment by Arkans428** [comment]
I've been able to send audio, sms, and dtmf tones, but for the audio i find that its hit and miss sometimes. Somedays it will connect right away and ill hear the audio perfectly (a short burst of static on the speakers usually occurs when it connects, not too sure why yet), other times it's just dead air on both ends of the call, including no DTMF. 
I'm still looking into why it's doing this, but i'll try a call a few times over until i hear that static burst followed by the ring tone of the call.

**Comment by truufseir** [comment]
that's exactly what i've noticed but i haven't got any audio how do i set up my mic and speakers

**Comment by truufseir** [comment]
Enter your choice: 2
Enter input device index: 8
Enter output device index: 3
Error starting audio streaming: BadDeviceId calling waveInOpen
Audio streaming started. Press any key to stop...

Enter your choice: 1
Index   Input Channels  Output Channels Name
0       0               2               Realtek Digital Output (Realtek(R) Audio)
1       0               2               LC32G5xT (NVIDIA High Definition Audio)
2       0               2               PRO (NVIDIA High Definition Audio)
3       0               2               Speakers (Focusrite USB Audio)
4       0               2               LG ULTRAWIDE (NVIDIA High Definition Audio)
5       2               0               Stereo Mix (Realtek(R) Audio)
6       1               0               Digital Audio Interface (Pyle PLINK1)
7       1               0               Microphone (Logi Webcam C920e)
8       2               0               Analogue 1 + 2 (Focusrite USB Audio)

**Comment by truufseir** [comment]
what do you think i was wondering if superpowered would work better let me know if you would like to try and i could help out instead of audio streamer

**Comment by truufseir** [comment]
i was wondering if you are just sending at commands or using some sort of modem manager to start and stop the call?

**Comment by Arkans428** [comment]
> that's exactly what i've noticed but i haven't got any audio how do i set up my mic and speakers

The SerialAudioPhone.cs class handles the audio device selection itself automatically. It will use the operating system's currently selected audio output and input devices. This can be set using Window's Sound Settings. Once you have you microphone and speakers set, the code should handle the rest.

**Comment by Arkans428** [comment]
Same goes with Linux, though i haven't fully tested it on my raspberry pi yet

**Comment by truufseir** [comment]
for some reason something is not working for the loop back test i sent you what it is saying

**Comment by Arkans428** [comment]
I've updated the code on my end and it's completely changed in regards to the structure.
I'll be uploading the update shortly once I get home.
